#!/usr/bin/env python3

import pathlib
import configparser
import argparse

from gandyndns import gandyndns

if __name__ == "__main__":
	parser = argparse.ArgumentParser()
	parser.add_argument('config', type=pathlib.Path, help='Path to gandyndns configuration file')
	parser.add_argument('--logging-level', type=int, help='Logging level')
	#parser.add_argument('--logging-handler', help='Logging handler')
	args = parser.parse_args()

	config = configparser.ConfigParser()
	config.read(str(args.config))

	for domain in config.sections():
		gandyndns_args = dict(config.items(domain))
		if args.logging_level:
			gandyndns_args['logging_level'] = args.logging_level
		gandyndns(domain, **gandyndns_args)
